title:        Prithviraj M Billa
tagline:      'Coder And Developer'
description:  'I love coding, theres going to lots of hacks comming now'
url:          http://blog.prithvirajbilla.com
version:      1.1.1
author:
  name:       'prithvirajbilla'
  email:      'prithviraj.m.billa@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
