title:        Prithviraj M Billa
tagline:      'RH/ Recreational Hacking'
description:  'Coding is cool!'
url:          'http://blog.prithvirajbilla.com'
author:
  name:       'prithvirajbilla'
  email:      'prithviraj.m.billa@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
